field: 8aa229ec-7643-48c3-947d-9d2c1882b8f2 # Content Blocks
fieldLayouts:
  681272f0-408c-4a02-a858-c83a4c88af93:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0bffb713-e477-48ff-af95-a978d91dcea3 # Button Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1e72352-2b30-46c0-b741-1794ad372cbd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1368596b-c204-434c-9222-b0a76112a5f2
        userCondition: null
fields:
  0bffb713-e477-48ff-af95-a978d91dcea3: # Button Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        craftCommerce-product:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources:
            - 'section:3f16d68f-cda8-49f7-8564-ba9db1855669' # Pages
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: button
name: Button
sortOrder: 4
